[colors]
draw_bold_text_with_bright_colors = true

[colors.cursor]
cursor = "#FFFFFF"
text = "#000000"


[env]
TERM = "xterm-256color"

[font]
size = 14

[font.normal]
family = "FiraCode Nerd Font Mono" 
style = "Regular"

[font.bold]
family = "FiraCode Nerd Font Mono"
style = "Bold"

[font.italic]
family = "FiraCode Nerd Font Mono"
style = "Italic"

[scrolling]
history = 10000
multiplier = 3

[window.padding]
x = 2
y = 6

[window.dimensions]
columns = 185
lines = 40

[selection]
save_to_clipboard = true
